"""add_inspector_counts

Revision ID: 548917107aee
Revises: 38cd650e63ff
Create Date: 2026-06-04 17:34:00.044475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548917107aee'
down_revision: Union[str, Sequence[str], None] = '38cd650e63ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'criterion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_constraint(op.f('fk_grades_reviewer'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'users', ['reviewer_id'], ['id'])
    op.add_column('groups', sa.Column('count_of_inspectors_expert', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('count_of_inspectors_student', sa.Integer(), nullable=True))
    # migrate existing counts from old column into new columns
    op.execute(
        """
        UPDATE groups
        SET
            count_of_inspectors_expert = CASE
                WHEN group_mode = 'CLASSIC' THEN count_of_inspectors
                ELSE 0
            END,
            count_of_inspectors_student = CASE
                WHEN group_mode = 'P2P' THEN count_of_inspectors
                ELSE 0
            END
        WHERE count_of_inspectors IS NOT NULL
        """
    )
    # make new columns non-nullable now that data is migrated
    op.alter_column('groups', 'count_of_inspectors_expert', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('groups', 'count_of_inspectors_student', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('groups', 'count_of_inspectors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('count_of_inspectors', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('groups', 'count_of_inspectors_student')
    op.drop_column('groups', 'count_of_inspectors_expert')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('fk_grades_reviewer'), 'grades', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.alter_column('grades', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'criterion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
